spring:
  application:
    name: restrauntAPI
  datasource:
    url: jdbc:postgresql://database:5432/restraunt_api
    username: postgres
    password: 1947
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true